### ISSUE TITLE
Delete assets?

### ISSUE THREAD

**Issue by danhunsaker** [Kellojo/github-release-notes-generator#1]
All the docs talk about deleting assets, but none of the code seems to actually delete anything. Is this left over from another action? I'd love to take advantage of the action, but I don't want anything deleted, in my case.

**Comment by Kellojo** [comment]
Hi @danhunsaker, I just looked at the code after quite a while and it does indeed look like I just copied this over from some other action. It should not delete anything on your side but rather leave you with a nice json containing your release notes 😄 

Nice to hear you're planning to use the action!
